name: Auto-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.0

    - name: Build
      run: |
        .\build.bat
        mkdir build 
        move Sonic_Selenium_1.gen build

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: nightly
        path: build
